apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-playwright-pipeline
spec:
  schedule: "*/10 * * * *" # every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: trigger
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl create -f - <<EOF
                  apiVersion: tekton.dev/v1
                  kind: PipelineRun
                  metadata:
                    generateName: playwright-pipeline-run-
                  spec:
                    pipelineRef:
                      name: playwright-pipeline
                    workspaces:
                      - name: output
                        emptyDir: {}
                  EOF
