apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: playwright-test
spec:
  workspaces:
    - name: output
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        git clone https://github.com/GauravTrapasiya/playwright-tekton.git /workspace/output
    - name: run-playwright
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
      workingDir: /workspace/output
      script: |
        npm install
        npx playwright install
        npx playwright test
